name: blackwell-train
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24
  - scipy=1.11
  - pandas=2.1
  - pyyaml=6.0
  - tqdm=4.65
  - zarr=2.16
  - numcodecs=0.11
  - hydra-core=1.2.0
  - wandb=0.15.8
  - dill=0.3.7
  - einops=0.6.1
  - python-lmdb=1.4
  - threadpoolctl=3.2
  - filelock
  - protobuf=4.25
  - click
  - matplotlib
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - protobuf==4.25.8
    - torch==2.7.0+cu128
    - torchvision==0.22.0+cu128
    - torchaudio==2.7.0+cu128
    - timm==0.9.7
    - diffusers==0.18.2
    - accelerate==0.24.1
    - huggingface_hub==0.25.2
    - imagecodecs==2023.9.18
    - av==17.0.1
    - opencv-python-headless==4.10.0.84
